######################## default configuration ####################
baseURL = "https://www.alasdoo.com/"
title = "ALAS doo"
theme = ["bigspring"]
# Default time zone for time stamps; use any valid [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List)
timeZone = "CET"
# post pagination
paginate = "6" # see https://gohugo.io/extras/pagination/
# post excerpt
summaryLength = "10" # see https://gohugo.io/content-management/excerpts/
# google analytics
googleAnalytics = "G-42X5WY85XG" # example: UA-123-45, for more info, read the article https://support.google.com/analytics/answer/1008080?hl=en
# disqus short name
disqusShortname = "" # we use disqus to show comments in blog posts . To install disqus please follow this tutorial https://portfolio.peter-baumgartner.net/2017/09/10/how-to-install-disqus-on-hugo/
# disable language
disableLanguages = [
] # example: ["de"] for disable deutsch language. see https://gohugo.io/content-management/multilingual/
hasCJKLanguage = false # If hasCJKLanguage true, auto-detect Chinese/Japanese/Korean Languages in the content.

[params]
homeTitle = "ALAS doo: Digital excellence in development, testing & accessibility"

############################# Modules ##############################
[module]
[module.hugoVersion]
extended = true
min = "0.111.0"

############################# Outputs ##############################
[outputs]
home = ["HTML", "RSS", "JSON", "WebAppManifest"]

############################# Imaging ##############################
[imaging]
# See https://github.com/disintegration/imaging
# Default JPEG or WebP quality setting. Default is 75.
quality = 100

############################# Caches ###############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"


############################# Markup ###############################
[related]
includeNewer = true
threshold = 80
toLower = false
[related.indices]
name = "keywords"
weight = 100


############################# Markup ###############################
[markup]
[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[markup.highlight]
style = 'monokai' # see https://xyproto.github.io/splash/docs/all.html

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true


############################ Media types ############################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

[mediaTypes."text/netlify"]
delimiter = ""
suffixes = [""]


############################ Output Format ###########################
[outputFormats]
[outputFormats.WebAppManifest]
mediaType = "application/manifest+json"
rel = "manifest"
