# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "What we do"
url = "/what-we-do/"
weight = 2

[[main]]
weight = 3
name = "Who we are"
url = "/who-we-are/"
hasChildren = true

[[main]]
parent = "Who we are"
name = "Our story"
url = "our-story/"
weight = 1

[[main]]
parent = "Who we are"
name = "Team"
url = "team/"
weight = 2

[[main]]
parent = "Who we are"
name = "Clients"
url = "clients/"
weight = 3


[[main]]
name = "Case Studies"
url = "/case-studies/"
weight = 4

[[main]]
name = "Careers"
url = "/careers/"
weight = 5

[[main]]
name = "Articles"
url = "/articles/"
weight = 6

# footer menu
[[footer_menu]]
name = "Home"
url = "/"
weight = 1

[[footer_menu]]
name = "Who We Are"
url = "/our-story/"
weight = 2

[[footer_menu]]
name = "What We Do"
url = "/what-we-do/"
weight = 3

# footer menu 2
[[footer_menu_2]]
name = "Case Studies"
url = "/case-studies/"
weight = 4

[[footer_menu_2]]
name = "Careers"
url = "/careers/"
weight = 5

[[footer_menu_2]]
name = "Articles"
url = "/articles/"
weight = 4

# # footer menu left
# [[footer_left]]
# name = "About Us"
# url = "about/"
# weight = 1

# [[footer_left]]
# name = "Team"
# url = "team/"
# weight = 2

# [[footer_left]]
# name = "How It Works"
# url = "how-it-works/"
# weight = 3

# [[footer_left]]
# name = "Career"
# url = "career/"
# weight = 4


# # footer menu middle
# [[footer_middle]]
# name = "Home"
# url = "/"
# weight = 1

# [[footer_middle]]
# name = "What We Do"
# url = "what-we-do/"
# weight = 2

# [[footer_middle]]
# name = "Who We Are"
# url = "who-we-are/"
# weight = 3

# [[footer_middle]]
# name = "Workplace"
# url = "products/product-3/"
# weight = 4

# [[footer_middle]]
# name = "Analytics"
# url = "products/product-4/"
# weight = 5

# # footer menu right
# [[footer_right]]
# name = "FAQ"
# url = "faq/"
# weight = 1

# [[footer_right]]
# name = "Contact"
# url = "contact/"
# weight = 2

# [[footer_right]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3

# [[footer_right]]
# name = "Terms & Conditions"
# url = "terms-conditions/"
# weight = 4
