# main menu
[[main]]
name = "Services"
url = "/services/"
weight = 2

[[main]]
weight = 3
name = "About us"
url = "/about-us/"
hasChildren = true

[[main]]
parent = "About us"
name = "Our story"
url = "our-story/"
weight = 1

[[main]]
parent = "About us"
name = "Our team"
url = "our-team/"
weight = 2

[[main]]
parent = "About us"
name = "Our clients"
url = "our-clients/"
weight = 3

[[main]]
name = "Case studies"
url = "/case-studies/"
weight = 4

[[main]]
name = "Careers"
url = "/careers/"
weight = 5

[[main]]
name = "Articles"
url = "/articles/"
weight = 6

[[main]]
name = "Contact us"
url = "/contact/"
weight = 7

# footer menu
[[footer_menu]]
name = "Services"
url = "/services/"
weight = 1

[[footer_menu]]
name = "Our story"
url = "our-story/"
weight = 2

[[footer_menu]]
name = "Our team"
url = "our-team/"
weight = 3

[[footer_menu]]
name = "Our clients"
url = "our-clients/"
weight = 4

# footer menu 2
[[footer_menu_2]]
name = "Case Studies"
url = "/case-studies/"
weight = 5

[[footer_menu_2]]
name = "Careers"
url = "/careers/"
weight = 6

[[footer_menu_2]]
name = "Articles"
url = "/articles/"
weight = 7

[[footer_menu_2]]
name = "Contact us"
url = "/contact/"
weight = 8


# copyright menu
[[copyright_menu]]
name = "Cookies"
url = "/cookies/"
weight = 7

[[copyright_menu]]
name = "Privacy Policy"
url = "/privacy-policy/"
weight = 8

[[copyright_menu]]
name = "Accessibility"
url = "/accessibility/"
weight = 9

[[copyright_menu]]
name = "Site map"
url = "/sitemap/"
weight = 9

# # footer menu left
# [[footer_left]]
# name = "About Us"
# url = "about/"
# weight = 1

# [[footer_left]]
# name = "Team"
# url = "team/"
# weight = 2

# [[footer_left]]
# name = "How It Works"
# url = "how-it-works/"
# weight = 3

# [[footer_left]]
# name = "Career"
# url = "career/"
# weight = 4


# # footer menu middle
# [[footer_middle]]
# name = "Home"
# url = "/"
# weight = 1

# [[footer_middle]]
# name = "Services"
# url = "wservices"
# weight = 2

# [[footer_middle]]
# name = "About us"
# url = "about-us/"
# weight = 3

# [[footer_middle]]
# name = "Workplace"
# url = "products/product-3/"
# weight = 4

# [[footer_middle]]
# name = "Analytics"
# url = "products/product-4/"
# weight = 5

# # footer menu right
# [[footer_right]]
# name = "FAQ"
# url = "faq/"
# weight = 1

# [[footer_right]]
# name = "Contact"
# url = "contact/"
# weight = 2

# [[footer_right]]
# name = "Privacy Policy"
# url = "privacy-policy/"
# weight = 3

# [[footer_right]]
# name = "Terms & Conditions"
# url = "terms-conditions/"
# weight = 4
